<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D12" Version="3.6.2" />
    <PackageReference Include="Vortice.DXGI" Version="3.6.2" />
    <PackageReference Include="Vortice.Mathematics" Version="1.9.2" />
    <ProjectReference Include="..\FunnyGame.Shared\FunnyGame.Shared.csproj" />
  </ItemGroup>
</Project>
