<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct3D12" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    <PackageReference Include="Vortice.Mathematics" Version="2.1.0" />
    <ProjectReference Include="..\FunnyGame.Shared\FunnyGame.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Shaders\Scene.hlsl" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
